name: "GraphQL Compose: Fragments"
description: "Extend fragment capabilities for use with GraphQL."
type: module
core_version_requirement: ^10.2 || ^11
php: 8.1
dependencies:
  - graphql_compose:graphql_compose
package: GraphQL Compose (Contrib)
hidden: false
configure: graphql_compose.fragments

# Information added by Drupal.org packaging script on 2024-09-15
version: '1.0.0'
project: 'graphql_compose_fragments'
datestamp: 1726440817
